### ISSUE TITLE
Ip Change

### ISSUE THREAD

**Issue by AbdulR3hman** [M94antony/AMD-Front-End-Seed#1]
@M94antony 

Is there anyway I can change the IP that is served on? 

trying to run this from a Vagrant Box

**Comment by AbdulR3hman** [comment]
@M94antony I setup the vagrant box, its serving the correct pages now. 

Whats next?

**Comment by mantony9000** [comment]
you can change the ip
its in the gulpfile.js
use this : https://www.browsersync.io/docs/options
